### ISSUE TITLE
Get template version and download...(node:80537) UnhandledPromiseRejectionWarning: Error: Command failed: npm pack @hummer/cli-template-vue@0.1.0 --registry=https://registry.npm.taobao.org/

### ISSUE THREAD

**Issue by zrunker** [OrangeLab/hummer-cli#20]
hummer init
? Which template do you want init? template-vue
? Project name hummer_vue
⠋ Get template version and download...(node:80537) UnhandledPromiseRejectionWarning: Error: Command failed: npm pack @hummer/cli-template-vue@0.1.0 --registry=https://registry.npm.taobao.org/
npm ERR! code EHOSTUNREACH
npm ERR! errno EHOSTUNREACH
npm ERR! request to https://cdn.npm.taobao.org/%40hummer/cli-template-vue/-/%40hummer/cli-template-vue-0.1.0.tgz failed, reason: connect EHOSTUNREACH 101.206.201.226:443

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/didi/.npm/_logs/2021-04-09T04_03_40_741Z-debug.log

    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at InitPlugin.getTempatePath (/usr/local/lib/node_modules/@hummer/cli/node_modules/@hummer/cli-plugin-init/dist/index.js:95:29)
    at /usr/local/lib/node_modules/@hummer/cli/node_modules/@hummer/cli-plugin-init/dist/index.js:53:43
    at new Promise (<anonymous>)
...

npm config set strict-ssl false
取消ssl认证，关闭vpn重试，可以解决问题

**Comment by duanlikang** [comment]
#### 问题原因
证书验证失败

#### 解决方案
1. 取消ssl认证，执行`npm config set strict-ssl false`
2. 检查是否有 VPN，关闭 VPN后重试
