### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir '/usr/local/lib/node_modules/@hummer/cli/node_modules/.hummer/cli-templates/hummer-cli-template-vue-0.1.0/package/template'

### ISSUE THREAD

**Issue by zrunker** [OrangeLab/hummer-cli#21]
Hummer Init 时异常
![image](https://user-images.githubusercontent.com/10548952/114150547-c49c2b80-994e-11eb-9973-df4354cf0fe1.png)

**Comment by duanlikang** [comment]
#### 原因
由于Init时模板工程做了缓存，会判断当前模板本地是否存在，如果存在，直接进行渲染创建。由于首次下载时，尚未下载完毕被中断，导致异常。

#### 解决方案
清空对应的缓存目录，以上图举例，应该清空 `/usr/local/lib/node_modules/@hummer/cli/node_modules/.hummer/cli-templates`文件夹，后重新安装即可。
