### ISSUE TITLE
IP地址变化导致热更新能力失效

### ISSUE THREAD

**Issue by bbssyyuui** [OrangeLab/hummer-cli#24]
在网络变化后（IP地址发生变化），不重启hummer dev，App重新连接新的IP对应的WebSocket之后，WebSocket返回的Msg中的url还是老的url，导致热更新能力失效。

![image](https://user-images.githubusercontent.com/3355750/116070612-6e094e00-a6bf-11eb-8500-996a76c48f65.png)

**Comment by duanlikang** [comment]
ip变化后，Websocket 拼接的ip地址需要进行更新，采用实时的最新的ip，保证原有的 hummer dev 仍然可以使用
