### ISSUE TITLE
更新cli版本至 0.13.1 后启动报错

### ISSUE THREAD

**Issue by dxeg** [OrangeLab/hummer-cli#55]
更新@hummer/cli 至0.13.1后，使用template-vue创建工程后启动报错

![image](https://github.com/OrangeLab/hummer-cli/assets/3794710/ecdac5b4-153f-4b0c-90ad-4cd0aba9121f)

运行时报错
![image](https://github.com/OrangeLab/hummer-cli/assets/3794710/35fd2a1d-7de8-4228-a966-68a8c0892df9)

**Comment by AdamCaoQAQ** [comment]
> 更新@hummer/cli 至0.13.1后，使用template-vue创建工程后启动报错
> 
> ![image](https://private-user-images.githubusercontent.com/3794710/293148004-ecdac5b4-153f-4b0c-90ad-4cd0aba9121f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjM4NDgsIm5iZiI6MTcwNzEyMzU0OCwicGF0aCI6Ii8zNzk0NzEwLzI5MzE0ODAwNC1lY2RhYzViNC0xNTNmLTRiMGMtOTBhZC00Y2QwYWJhOTEyMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMDg1OTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWYyYmVlZWFlODhjNzI1OGE1ZGVhNjE4ZGM0NDc1ZmNiNWFkNWZlYWIxMGExZTQ5NWMzYzk2NTM2NDBkOWUzYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zVyW3H8E6dTML9EOOajORJhTH8qhr8uZxJyvHWxvK6U)
> 
> 运行时报错 ![image](https://private-user-images.githubusercontent.com/3794710/293148811-35fd2a1d-7de8-4228-a966-68a8c0892df9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjM4NDgsIm5iZiI6MTcwNzEyMzU0OCwicGF0aCI6Ii8zNzk0NzEwLzI5MzE0ODgxMS0zNWZkMmExZC03ZGU4LTQyMjgtYTk2Ni02OGE4YzA4OTJkZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMDg1OTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzNmNTIzODk4OWQ5MmJjMWQ2MjRhYjViOTFmYzNmZjhjNWNlNjVjNWU1MmQ0M2I4OTBjNDQyY2Y4MDc4YzYyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L6Wpw1MbLEiXkpbVvDB0AecO3I9EJGArDjGzRnvXuKU)

**感谢反馈，确诊为BUG，将于近期修复：）**
临时方案可以以将项目中 _@hummer/tenon-vue_ 版本降级至1.8.3；同时将 _@hummer/cli_ （安装目录可以通过执行`hummer -v `找到）中 _@hummer/tenon-loader_ 版本降级至1.2.0

**Comment by AdamCaoQAQ** [comment]
> 更新@hummer/cli 至0.13.1后，使用template-vue创建工程后启动报错
> 
> ![image](https://private-user-images.githubusercontent.com/3794710/293148004-ecdac5b4-153f-4b0c-90ad-4cd0aba9121f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjc0MTEsIm5iZiI6MTcwNzEyNzExMSwicGF0aCI6Ii8zNzk0NzEwLzI5MzE0ODAwNC1lY2RhYzViNC0xNTNmLTRiMGMtOTBhZC00Y2QwYWJhOTEyMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMDk1ODMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzAxMzc0N2QwMGZhMTM3NDE2ZjgzN2Q3MjAxNjdkMzcxM2JkZmM4ZTljOGNjNzVlMGZiYWVmZTRkYTNmNzkwYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZtjNjzMB2yrgCpElDcTwh7SfEOAWECX29RPx2TgQOXs)
> 
> 运行时报错 ![image](https://private-user-images.githubusercontent.com/3794710/293148811-35fd2a1d-7de8-4228-a966-68a8c0892df9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjc0MTEsIm5iZiI6MTcwNzEyNzExMSwicGF0aCI6Ii8zNzk0NzEwLzI5MzE0ODgxMS0zNWZkMmExZC03ZGU4LTQyMjgtYTk2Ni02OGE4YzA4OTJkZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMDk1ODMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmViMWY3ZGFkMmUwZGUxODg2MjA1NGViMzY4OWMxMzE4MzRlYjYyODRjMDQ0MGU4ZjQxOWQ0Y2E1YThhNDc0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.41TnQgzdr8bmEB81L-7fFH02ZuDudiQVPHbqXqYWSBg)

_@hummer/cli_ 现已升级至0.14.0  上述报错已验证修复，请升级后再次尝试
